import React from 'react';
import { Box, Container, Heading, Text, VStack, UnorderedList, ListItem, Link as ChakraLink } from '@chakra-ui/react';

export default function PrivacyPolicy() {
  // DISCLAIMER: This is placeholder content generated by an AI. It is NOT legal advice.
  // Consult with a qualified legal professional to ensure compliance.
  return (
    <Box py={{ base: 12, md: 20 }} px={{ base: 4, md: 8 }}>
      <Container maxW="container.md"> {/* Slightly narrower for readability */}
        <VStack spacing={8} align="stretch">
          <Heading as="h1" size="xl" textAlign="center" mb={6}>
            Privacy Policy for Clipzy
          </Heading>
          
          <Text textAlign="center" fontStyle="italic" color="gray.600">
            Effective Date: {new Date().toLocaleDateString()}
          </Text>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">1. Introduction</Heading>
            <Text>
              Welcome to Clipzy! This Privacy Policy explains how Nyx Solutions ("Clipzy", "we", "us", or "our") collects, uses, shares, and protects information in relation to our website and AI-powered fashion imagery generation services (collectively, the "Service"). Your privacy is important to us, and we are committed to protecting it through our compliance with this policy. This policy applies to information we collect on the Service and in email, text, and other electronic messages between you and the Service.
            </Text>
          </VStack>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">2. Information We Collect</Heading>
            <Text>
              We collect several types of information from and about users of our Service, including:
            </Text>
            <UnorderedList pl={6} spacing={2}>
              <ListItem>
                <strong>Personal Information:</strong> Information by which you may be personally identified, such as name, email address, password, and payment information (processed by a third-party payment processor, we typically do not store full payment card details).
              </ListItem>
              <ListItem>
                <strong>Uploaded Content:</strong> Images, designs, prompts, or other files you upload to the Service for processing. We collect this to provide the core functionality of the Service.
              </ListItem>
              <ListItem>
                <strong>Generated Content:</strong> The AI-generated images and related data created through your use of the Service. We store this content to make it available to you.
              </ListItem>
              <ListItem>
                <strong>Usage Information:</strong> Details of your visits to our Service, including traffic data, logs, features used, AI model interactions (anonymized where possible), and other communication data and the resources that you access and use on the Service.
              </ListItem>
              <ListItem>
                <strong>Device Information:</strong> Information about your computer or mobile device and internet connection, including your IP address, operating system, and browser type.
              </ListItem>
              <ListItem>
                <strong>Cookies and Tracking Technologies:</strong> We use cookies (or browser cookies) and other tracking technologies to collect information about your browsing activities over time and across different websites following your use of our Service. You can control cookie settings through your browser.
              </ListItem>
            </UnorderedList>
          </VStack>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">3. How We Use Your Information</Heading>
            <Text>
              We use information that we collect about you or that you provide to us, including any personal information:
            </Text>
             <UnorderedList pl={6} spacing={2}>
              <ListItem>To present our Service and its contents to you.</ListItem>
              <ListItem>To provide you with information, products, or services that you request from us.</ListItem>
              <ListItem>To fulfill the core purpose of the Service, i.e., generating fashion imagery based on your inputs.</ListItem>
              <ListItem>To process your payments for subscription or usage fees.</ListItem>
              <ListItem>To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection.</ListItem>
              <ListItem>To notify you about changes to our Service or any products or services we offer or provide through it.</ListItem>
              <ListItem>To improve our Service, including training our AI models (where appropriate and ideally using anonymized or aggregated data, or data for which explicit consent for training has been obtained - *this needs specific legal review based on actual practice*).</ListItem>
              <ListItem>To monitor usage, prevent fraud, and enhance the security of our Service.</ListItem>
              <ListItem>For any other purpose with your consent.</ListItem>
            </UnorderedList>
          </VStack>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">4. Disclosure of Your Information</Heading>
            <Text>
              We are committed to maintaining your trust, and we want you to understand when and with whom we may share the information we collect. We do not sell your personal information.
            </Text>
            <Text>We may disclose personal information that we collect or you provide as described in this privacy policy:</Text>
             <UnorderedList pl={6} spacing={2}>
              <ListItem>To our subsidiaries and affiliates.</ListItem>
              <ListItem>To contractors, service providers, and other third parties we use to support our business (e.g., hosting providers, payment processors, analytics providers) and who are bound by contractual obligations to keep personal information confidential and use it only for the purposes for which we disclose it to them.</ListItem>
              <ListItem>To fulfill the purpose for which you provide it.</ListItem>
              <ListItem>To comply with any court order, law, or legal process, including to respond to any government or regulatory request.</ListItem>
              <ListItem>To enforce or apply our terms of service and other agreements, including for billing and collection purposes.</ListItem>
              <ListItem>If we believe disclosure is necessary or appropriate to protect the rights, property, or safety of Clipzy, our customers, or others.</ListItem>
              <ListItem>In connection with a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Clipzy's assets.</ListItem>
              <ListItem>For any other purpose disclosed by us when you provide the information or with your consent.</ListItem>
              <ListItem>We may share aggregated or anonymized information that does not identify any individual without restriction.</ListItem>
            </UnorderedList>
          </VStack>
          
          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">5. Your Rights and Choices</Heading>
            <Text>
              Depending on your location and applicable law, you may have certain rights regarding the personal information we hold about you. These may include the right to:
            </Text>
            <UnorderedList pl={6} spacing={2}>
              <ListItem>Access and receive a copy of your personal information.</ListItem>
              <ListItem>Rectify any inaccurate or incomplete personal information.</ListItem>
              <ListItem>Request deletion of your personal information, subject to certain exceptions.</ListItem>
              <ListItem>Object to or restrict the processing of your personal information in certain circumstances.</ListItem>
              <ListItem>Data portability, where applicable.</ListItem>
              <ListItem>Withdraw consent, where processing is based on consent.</ListItem>
              <ListItem>Opt-out of certain data uses (like marketing communications).</ListItem>
            </UnorderedList>
            <Text>You can typically review and change your personal information by logging into the Service and visiting your account profile page. To exercise other rights, please contact us using the contact information below.</Text>
          </VStack>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">6. Data Security</Heading>
            <Text>
              We have implemented measures designed to secure your personal information from accidental loss and from unauthorized access, use, alteration, and disclosure. All payment transactions are encrypted using SSL technology. However, the transmission of information via the internet is not completely secure. Although we do our best to protect your personal information, we cannot guarantee the security of your personal information transmitted to our Service. Any transmission of personal information is at your own risk.
            </Text>
          </VStack>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">7. Data Retention</Heading>
            <Text>
              We retain your personal information for as long as necessary to provide the Service and fulfill the transactions you have requested, or for other essential purposes such as complying with our legal obligations, resolving disputes, and enforcing our agreements. Uploaded and Generated Content may be retained according to your subscription plan or account status, or until you delete it, subject to our internal backup and retention policies.
            </Text>
          </VStack>

           <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">8. Children's Privacy</Heading>
            <Text>
              Our Service is not intended for children under the age of 13 (or a higher age threshold where applicable). We do not knowingly collect personal information from children under 13. If we learn we have collected or received personal information from a child under 13 without verification of parental consent, we will delete that information.
            </Text>
          </VStack>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">9. Changes to Our Privacy Policy</Heading>
            <Text>
              It is our policy to post any changes we make to our privacy policy on this page. If we make material changes to how we treat our users' personal information, we will notify you through a notice on the Service home page or via email. The date the privacy policy was last revised is identified at the top of the page.
            </Text>
          </VStack>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">10. Contact Information</Heading>
            <Text>
              To ask questions or comment about this privacy policy and our privacy practices, contact us at:
              [Your Company Name/Contact Email]
              [Your Company Address, if applicable]
              {/* Replace with actual contact info */}
            </Text>
          </VStack>

        </VStack>
      </Container>
    </Box>
  );
} 