import React from 'react';
import { Box, Container, Heading, Text, VStack, UnorderedList, ListItem, Link as ChakraLink } from '@chakra-ui/react';

export default function TermsOfService() {
  // DISCLAIMER: This is placeholder content generated by an AI. It is NOT legal advice.
  // Consult with a qualified legal professional to ensure compliance.
  return (
    <Box py={{ base: 12, md: 20 }} px={{ base: 4, md: 8 }}>
      <Container maxW="container.md"> {/* Slightly narrower for readability */}
        <VStack spacing={8} align="stretch">
          <Heading as="h1" size="xl" textAlign="center" mb={6}>
            Terms of Service for Clipzy
          </Heading>
          
          <Text textAlign="center" fontStyle="italic" color="gray.600">
            Effective Date: {new Date().toLocaleDateString()}
          </Text>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">1. Acceptance of Terms</Heading>
            <Text>
              These Terms of Service ("Terms") govern your access to and use of the Clipzy website and AI-powered fashion imagery generation services (collectively, the "Service") provided by Nyx Solutions ("Clipzy", "we", "us", or "our"). By accessing or using the Service, you agree to be bound by these Terms. If you do not agree to these Terms, you may not access or use the Service. We may modify these Terms at any time, and such modifications shall be effective immediately upon posting the modified Terms on the Service.
            </Text>
          </VStack>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">2. Description of Service</Heading>
            <Text>
              Clipzy provides a platform enabling users to upload images and text prompts to generate unique fashion-related visual content using artificial intelligence. Features, capabilities, and pricing are subject to change and may vary based on subscription plans or usage tiers. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We do not guarantee that the Service will be uninterrupted or error-free.
            </Text>
          </VStack>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">3. User Accounts</Heading>
            <Text>
              To access certain features of the Service, you may be required to create an account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete. You are responsible for safeguarding your password and for any activities or actions under your account. You agree to notify us immediately of any unauthorized use of your account.
            </Text>
          </VStack>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">4. User Conduct and Responsibilities</Heading>
            <Text>
              You agree to use the Service only for lawful purposes and in accordance with these Terms. You are solely responsible for the content you upload ("Uploaded Content") and the content generated through your use ("Generated Content"), and for your conduct while using the Service. You agree not to use the Service to:
            </Text>
            <UnorderedList pl={6} spacing={2}>
              <ListItem>Upload, generate, or distribute any content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, invasive of another's privacy, hateful, or racially, ethnically, or otherwise objectionable.</ListItem>
              <ListItem>Infringe upon any patent, trademark, trade secret, copyright, right of publicity, or other proprietary rights of any party.</ListItem>
              <ListItem>Upload or transmit viruses, worms, or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet.</ListItem>
              <ListItem>Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the Service, the server on which the Service is stored, or any server, computer, or database connected to the Service.</ListItem>
               <ListItem>Attempt to reverse engineer, decompile, or otherwise derive the source code or underlying algorithms of the AI models used by the Service.</ListItem>
               <ListItem>Engage in any other conduct that restricts or inhibits anyone's use or enjoyment of the Service, or which, as determined by us, may harm Clipzy or users of the Service or expose them to liability.</ListItem>
            </UnorderedList>
          </VStack>

           <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">5. Content Ownership and Licenses</Heading>
            <Text>
              <strong>Your Content:</strong> You retain all ownership rights to your Uploaded Content. By submitting Uploaded Content to the Service, you grant Clipzy a limited, worldwide, non-exclusive, royalty-free license to use, reproduce, modify (e.g., for formatting), process, and display such content solely for the purpose of operating, providing, and improving the Service for you.
            </Text>
             <Text>
              <strong>Generated Content:</strong> Subject to your compliance with these Terms and payment of any applicable fees, Clipzy grants you full ownership and commercial rights to the unique Generated Content created by you through the Service during a paid subscription term or via paid credits. Clipzy makes no claims on the copyright of such Generated Content. (*Note: Ownership of AI-generated works can be complex and varies by jurisdiction; consult legal counsel.*)
            </Text>
             <Text>
              <strong>Service and AI Models:</strong> Clipzy retains all rights, title, and interest in and to the Service itself, including its underlying technology, AI models, software, trademarks, and visual design.
            </Text>
          </VStack>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">6. Fees and Payment</Heading>
            <Text>
              Certain aspects of the Service may require payment. You agree to pay all applicable fees as described on our pricing page or within the Service for the subscription plan or credits you select. All fees are non-refundable except as required by law or as explicitly stated otherwise. Subscription fees may automatically renew unless cancelled prior to the renewal date.
            </Text>
          </VStack>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">7. Intellectual Property Rights</Heading>
            <Text>
             The Service and its entire contents, features, and functionality (including but not limited to all information, software, text, displays, images, video, and audio, and the design, selection, and arrangement thereof) are owned by Clipzy, its licensors, or other providers of such material and are protected by international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.
             We respect the intellectual property rights of others. If you believe that your work has been copied in a way that constitutes copyright infringement, please provide us with the necessary information according to our Copyright Policy [Link to Policy, if separate].
            </Text>
          </VStack>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">8. Disclaimers</Heading>
            <Text>
              YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. CLIPZY EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE RESULTS OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE, RELIABLE, OR MEET YOUR REQUIREMENTS.
            </Text>
          </VStack>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">9. Limitation of Liability</Heading>
            <Text>
              TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL CLIPZY, ITS AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, SUPPLIERS OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (A) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE; (B) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE; (C) ANY CONTENT OBTAINED FROM THE SERVICE; OR (D) UNAUTHORIZED ACCESS, USE OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE) OR ANY OTHER LEGAL THEORY, WHETHER OR NOT WE HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE.
            </Text>
          </VStack>

           <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">10. Indemnification</Heading>
            <Text>
              You agree to defend, indemnify, and hold harmless Clipzy, its affiliates, licensors, and service providers, and its and their respective officers, directors, employees, contractors, agents, licensors, suppliers, successors, and assigns from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to your violation of these Terms or your use of the Service, including, but not limited to, your Uploaded Content, any use of the Service's content, services, and products other than as expressly authorized in these Terms or your use of any information obtained from the Service.
            </Text>
          </VStack>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">11. Termination</Heading>
            <Text>
              We may terminate or suspend your access to all or part of the Service, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease. You may terminate your account at any time through your account settings.
            </Text>
          </VStack>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">12. Governing Law and Dispute Resolution</Heading>
            <Text>
              These Terms shall be governed and construed in accordance with the laws of [Your Jurisdiction, e.g., State of California, USA], without regard to its conflict of law provisions. Any dispute arising from these Terms or the Service shall be resolved through [Specify Method, e.g., binding arbitration in a specific location, or courts of a specific location].
            </Text>
          </VStack>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">13. Miscellaneous</Heading>
            <Text>
             These Terms constitute the entire agreement between you and Clipzy regarding our Service and supersede and replace any prior agreements we might have had between us regarding the Service. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect.
            </Text>
          </VStack>

          <VStack spacing={4} align="stretch">
            <Heading as="h2" size="lg">14. Contact Information</Heading>
            <Text>
              Questions about the Terms of Service should be sent to us at [Your Company Contact Email].
            </Text>
          </VStack>

        </VStack>
      </Container>
    </Box>
  );
} 